[build]
  functions = "func"  # O diretório onde suas funções do Netlify vão ficar
  command = "pip install -r requirements.txt && python -m flask run"  # Comando de build
  


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200