[build]
  functions = "functions"  # Diretório onde suas funções do Netlify (se houver) estão localizadas
  command = "pip install -r requirements.txt && python app.py"  # Comando para instalar dependências e rodar a app
  publish = "dist"  # Diretório onde o projeto será publicado (ajuste conforme necessário)

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200